### ISSUE TITLE
Cannot use CopySpec's expand in the RPM task

### ISSUE THREAD

**Issue by sshcherbakov** [TrigonicSolutions/gradle-rpm-plugin#57]
It would be very convenient to be able to use `CopySpec`'s `expand` in the `Rpm` task:

```
task distRpm(type:Rpm) {
    ...
    expand( [myprop, 'myval']  )
}
```

At the moment (version 1.4) the above code throws exception during build:

```
4:31:50.548 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.UnsupportedOperationException
14:31:50.548 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.file.copy.DefaultFileCopyDetails.getFile(DefaultFileCopyDetails.java:55)
14:31:50.549 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:160)
14:31:50.549 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.BeanDynamicObject.getProperty(BeanDynamicObject.java:114)
14:31:50.550 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.file.copy.DefaultFileCopyDetails_Decorated.getProperty(Unknown Source)
14:31:50.550 [ERROR] [org.gradle.BuildExceptionReporter]    at com.trigonic.gradle.plugins.rpm.RpmCopySpecVisitor.visitFile(RpmCopySpecVisitor.groovy:81)
14:31:50.551 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.file.copy.NormalizingCopySpecVisitor.visitFile(NormalizingCopySpecVisitor.java:74)
14:31:50.551 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.file.copy.DelegatingCopySpecVisitor.visitFile(DelegatingCopySpecVisitor.java:48)
14:31:50.552 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.file.copy.DuplicateHandlingCopySpecVisitor.visitFile(DuplicateHandlingCopySpecVisitor.java:48)
14:31:50.552 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.file.copy.CopySpecVisitorDriver$1.visitFile(CopySpecVisitorDriver.java:54)
14:31:50.552 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.file.collections.DirectoryFileTree.walkDir(DirectoryFileTree.java:156)
14:31:50.553 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.file.collections.DirectoryFileTree.walkDir(DirectoryFileTree.java:171)
14:31:50.553 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.file.collections.DirectoryFileTree.visitFrom(DirectoryFileTree.java:124)
14:31:50.554 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.file.collections.DirectoryFileTree.visit(DirectoryFileTree.java:114)
14:31:50.554 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.file.collections.FileTreeAdapter.visit(FileTreeAdapter.java:96)
14:31:50.555 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.file.CompositeFileTree.visit(CompositeFileTree.java:54)
14:31:50.555 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.file.copy.CopySpecVisitorDriver.visit(CopySpecVisitorDriver.java:41)
14:31:50.556 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.file.copy.CopyActionImpl.execute(CopyActionImpl.java:65)
14:31:50.556 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.tasks.AbstractCopyTask.copy(AbstractCopyTask.java:42)
14:31:50.557 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:248)
14:31:50.557 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:136)
14:31:50.558 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:147)
14:31:50.558 [ERROR] [org.gradle.BuildExceptionReporter]    at com.trigonic.gradle.plugins.rpm.Rpm_Decorated.invokeMethod(Unknown Source)
14:31:50.559 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:248)
14:31:50.559 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:136)
14:31:50.560 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:147)
14:31:50.560 [ERROR] [org.gradle.BuildExceptionReporter]    at com.trigonic.gradle.plugins.rpm.Rpm_Decorated.invokeMethod(Unknown Source)
14:31:50.561 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.util.ReflectionUtil.invoke(ReflectionUtil.groovy:23)
14:31:50.561 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:220)
14:31:50.561 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:213)
14:31:50.562 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:202)
14:31:50.562 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:530)
14:31:50.563 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:513)
14:31:50.563 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
14:31:50.563 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
```

**Comment by shishirvicto** [comment]
CopySpecImpl extends EmptyCopySpecVisitor.

it did not find EmptyCopySpecVisitor.

gradle-rpm-plugin/src/main/groovy/com/trigonic/gradle/plugins/rpm/RpmCopySpecVisitor.groovy: 23: unable to resolve class org.gradle.api.internal.file.copy.EmptyCopySpecVisitor
